### ISSUE TITLE
Add `~'*` to the keyword list

### ISSUE THREAD

**Issue by trag1c** [samarium-lang/vscode-samarium#10]
Samarium 0.4.0 will introduce static methods represented by the `~'*` token. Currently, they're highlighted separately as operators and keywords. It should instead be treated as its own keyword.

**Comment by sujal-goswami** [comment]
can you tell me what I have to do in this issue?

**Comment by trag1c** [comment]
> can you tell me what I have to do in this issue?

It's exactly the same thing as your previous PR, just `~'*` instead of `<=`.
