### ISSUE TITLE
Add `<=` to the keyword list

### ISSUE THREAD

**Issue by trag1c** [samarium-lang/vscode-samarium#11]
Pretty much the same as #10.

**Comment by sujal-goswami** [comment]
hello, trag1c I want to work on this issue can you assign this to me.

**Comment by trag1c** [comment]
sure thing

**Comment by sujal-goswami** [comment]
hey can you tell where I supposed to find keyword list to add it.

**Comment by trag1c** [comment]
`syntaxes/samarium.tmLanguage.json`; it should be in the `operators` section

**Comment by sujal-goswami** [comment]
is i have to add `<=` keyword to  "name": "keyword.control.samarium"  section or  in "name": "keyword.operator.samarium" section

**Comment by trag1c** [comment]
`keyword.control.samarium`
